apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shifumi-deployer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vfiftyfive/argocd-shifumi-deployer.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

