apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clientintents
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/vfiftyfive/shifumi-app-policies.git
    targetRevision: HEAD
    path: clientintents
  destination:
    server: https://kubernetes.default.svc
    namespace: shifumi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
